# Generated by Django 5.2.1 on 2025-05-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('my_name', models.CharField(max_length=100)),
                ('my_photo', models.ImageField(upload_to='photos/')),
                ('my_email', models.EmailField(max_length=254)),
                ('my_phone', models.CharField(max_length=20)),
                ('head_name', models.CharField(max_length=100)),
                ('head_photo', models.ImageField(upload_to='photos/')),
                ('head_email', models.EmailField(max_length=254)),
                ('manager_name', models.CharField(max_length=100)),
                ('manager_photo', models.ImageField(upload_to='photos/')),
                ('manager_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('М', 'Мужской'), ('Ж', 'Женский')], max_length=1)),
                ('email', models.EmailField(max_length=254)),
                ('course', models.IntegerField()),
                ('average_score', models.FloatField()),
            ],
        ),
    ]
